// <auto-generated />
namespace Lunch_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adaptModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adaptModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201605051631152_adaptModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
